# default parameters for lane_filter/lane_filter_node

debug : True
predict_frequency: 30.0 # in Hz
lane_filter_histogram_configuration:
  # ADD PARAMETERS HERE
  mean_d_0: 0
  mean_phi_0: 0
  sigma_d_0: 0.1
  sigma_phi_0: 0.1
  delta_d: 0.018
  delta_phi: 0.08
  d_max: 0.5
  d_min: -0.2
  phi_min: -0.9
  phi_max: 0.9
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  sigma_d_mask: 1.0
  sigma_phi_mask: 2.5
  encoder_resolution: 135
  wheel_radius: 0.0318
  wheel_baseline: 0.1
